server:
  port: 8001

spring:
  application:
    name: micro-service-provider

eureka:
  client:    # 客户端注册服务到eureka列表中
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: micro-service-provider-8001    # 配置在eureka列表中显示的ID
    prefer-ip-address: true    # 访问路径可以显示IP地址，而不是主机名

info:
  app.name: ashitaka's micro-springcloud-service
  company.name: www.baidu.com
  application.name: ${spring.application.name}